### ISSUE TITLE
The data folder is missing

### ISSUE THREAD

**Issue by Vuwij** [pfrommerd/tag-tracking-matlab#1]

**Comment by pfrommerd** [comment]
Sorry about that, the data files are rather large.

You can download a tar of the test data at
https://drive.google.com/file/d/1rRDUwXjWUyByaXgeZmLG7RkyI56dOKlL/view?usp=sharing

You might have to change some of the parameters around since I probably modified them since I tested that dataset. I'm trying to find a place to host the rest of the data and so might move it eventually to somewhere more permanent.

**Comment by Vuwij** [comment]
Thanks for the help

Jason
